### ISSUE TITLE
Button Placement

### ISSUE THREAD

**Issue by Dumbaz** [MeoMix/StreamusWebsite#29]
Would you consider moving the "Donate Bitcoins" Button just a little bit?

![Image of Donation Page](http://puu.sh/gmTAR/7c216b2082.png)

**Comment by MeoMix** [comment]
The whole website is going to get overhauled pretty soon. I realize it
looks a bit poor, but I just don't put a ton of time working on it
compared to the extension itself.

**Comment by Dumbaz** [comment]
I actually like the Website, it´s just that this one Button looks like it´s clipping into the fields.

**Comment by MeoMix** [comment]
Well, feel free to submit a PR to bump it down a few pixels :p Or I'll get
to it asap.

**Comment by MeoMix** [comment]
I fixed it up in the new dev version. Should be live this weekend.
